### PR TITLE
Enharmonic chords and more

### PR DESCRIPTION
**Pull request by Matt54**
Added some enharmonic chords as well as some additional chords and intervals

Added ability to get all enharmonic chords for a given NoteSet

Added tests for enharmonic chords

Updated Demo

https://user-images.githubusercontent.com/15333030/202714758-5301758a-3f26-41ba-b820-8322d2b21e1c.mov

### CODE REVIEW

**Comment by NickCulbertson** [comment]
There was an issue before where the intervals needed to be in either alphabetic or numeric order (I can't remember which).

```case .m6: return 8
         case .M6: return 9
         case .A6: return 10
         case .d7: return 9
         case .m7: return 10
         case .M7: return 11``` 

.d7 might need to be moved before .M6 but I'm not sure.

**Comment by Matt54** [comment]
> There was an issue before where the intervals needed to be in either alphabetic or numeric order (I can't remember which).
> 
> ```
>          case .m6: return 8
>          case .M6: return 9
>          case .A6: return 10
>          case .d7: return 9
>          case .m7: return 10
>          case .M7: return 11
> ```
> 
> .d7 might need to be moved before .M6 but I'm not sure.

Thanks! Updated the order of the interval semitones cases

**Comment by aure** [comment]
It would be great if tests could touch some of these additions.

**Comment by Matt54** [comment]
> It would be great if tests could touch some of these additions.

Sure - I can add some tests. I thought to do so, but it looks like the current tests don't cover each ChordType and Interval, so I wasn't sure what we were looking for

**Comment by Matt54** [comment]
Screen Shot 2022-11-15 at 12 01 26 PM

Interesting! It's returning an inversion...

**Comment by Matt54** [comment]
> 

Makes sense. It doesn't bother me that the Chord initializer makes an arbitrary selection. 

I'm working on an app that converts a single pitch to a chord, so I need the many chords that use the pitch for the root

Is there a known issue that enharmonic chords will cause others?

**Comment by Matt54** [comment]
Btw I added some tests and fixed any existing tests broken by the additions

**Review by aure — APPROVED** [review]

**Pull request merged**
