### PR TITLE
Fix bug "If shiftup results in b#, octave is wrong"

### PR DESCRIPTION
**Pull request by saito-arch**
#26 
I took care of this issue.  
Perhaps variable name "carrying" should be changed.
I don't know much about music-theory, so I can't give it a proper name.

### CODE REVIEW

**Comment by aure** [comment]
Can you write tests that show how this is fixed? I posted some code today that dealt with Cb issues, so I assume this is related.

**Comment by aure** [comment]
I'm concerned that the code isn't very clear. "Carrying" is suspect, I agree, but there's more than that which is bothering me. Maybe the better thing to do would be to write some tests that show what is broken and then I'll have a look to see what's the best way of fixing it.

**Comment by saito-arch** [comment]
I add tests about #26 .
In my environment, there are two elements instead of three.

**Comment by saito-arch** [comment]
We should calculate octave by using the midiNoteNumber of the new note without accidental.
I intended to write calculateOctave.

**Comment by saito-arch** [comment]
I would like to know the appropriate example, as it should be tested even for shiftDown.

**Comment by saito-arch** [comment]
I'm sorry.
There was a problem with this solution.
Please see #36.

**Pull request closed without merging**
